# Should be the INDEX DIGEST from an image tagged `bookworm-<DATE>-slim`:
#     https://hub.docker.com/_/debian/tags?name=trixie-
#
# Tag for this digest: trixie-20260518-slim
DEBIAN_IMAGE_DIGEST=sha256:b6e2a152f22a40ff69d92cb397223c906017e1391a73c952b588e51af8883bf8
# Can be bumped to today's date
DEBIAN_ARCHIVE_DATE=20260610
# Can be bumped to the latest date in https://github.com/google/gvisor/tags
GVISOR_ARCHIVE_DATE=20260601
